name: Midterm Exam Deploy to ECR

on: 
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: midterm-ecr-jimeng
        IMAGE_TAG: v0.1
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:midterm-webapp-image-$IMAGE_TAG .
        docker network create midterm-network
        docker run -d --name midterm-webapp-container --network midterm-network -p 8081:5000 -e PORT=5000 $ECR_REGISTRY/$ECR_REPOSITORY:midterm-webapp-image-$IMAGE_TAG
        docker ps
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:midterm-webapp-image-$IMAGE_TAG
